# Generated by Django 3.2.21 on 2024-02-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('place', models.FileField(upload_to='')),
                ('post', models.FileField(upload_to='')),
                ('pin', models.FileField(upload_to='')),
                ('qualification', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('healthcondition', models.CharField(max_length=100)),
                ('CARETAKERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='work_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CARETAKERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='pillreminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_oftimes', models.BigIntegerField()),
                ('days', models.BigIntegerField()),
                ('PATIENTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patients_needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CARETAKERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.caretaker')),
                ('PATIENTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patientrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('PATIENTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CAMERAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.camera')),
            ],
        ),
        migrations.CreateModel(
            name='medicine_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CAMERAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.camera')),
                ('PATIENTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('CARETAKERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.caretaker')),
            ],
        ),
        migrations.AddField(
            model_name='caretaker',
            name='LOGINID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.login_table'),
        ),
    ]
