# Generated by Django 3.2.21 on 2024-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_auto_20240222_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillreminder',
            name='medicine',
            field=models.CharField(max_length=100),
        ),
    ]
