# Generated by Django 3.2.21 on 2024-02-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_alter_pillreminder_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
