# Generated by Django 3.2.21 on 2024-03-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_alter_patients_needs_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('PATIENTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.patient')),
            ],
        ),
    ]
