# Generated by Django 3.2.21 on 2024-03-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_medicine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_notification',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.medicine_table'),
        ),
    ]
