# Generated by Django 3.2.21 on 2024-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_fall_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall_detection',
            name='photo',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
