# Generated by Django 3.2.21 on 2024-03-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_fall_detection_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall_detection',
            name='CAMERAID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_app.camera'),
            preserve_default=False,
        ),
    ]
