# Generated by Django 3.2.21 on 2024-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0012_fall_detection_cameraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall_detection',
            name='condition',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
