# Generated by Django 3.2.21 on 2024-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0013_fall_detection_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
