# Generated by Django 3.2.21 on 2024-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0016_chat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
