# Generated by Django 3.2.21 on 2024-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0017_alter_chat_table_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
