# Generated by Django 3.2.21 on 2024-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0018_alter_chat_table_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='join_date',
            field=models.DateField(default='2024-04-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='admit_date',
            field=models.DateField(default='2024-04-24'),
            preserve_default=False,
        ),
    ]
