# Generated by Django 3.2.21 on 2024-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0019_auto_20240505_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
